n=input("So tien ban dau: ")
k=int(input("So thang gui: "))
T=float(input("Lai suat/ than:  "))
print("Voi so tien ban dau",str(n),"+","sau"+str(k),"thang gui, lai suat",T,"/thang")
print("Thi so tien nhan duoc cuoi ky lai",n*(1+k*T),sep="")